ots/accounts/urls.py
#from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.login_view, name="Home"),
]

ots/main/urls.py
#from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.homepage, name="list"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('bolaka/', views.bolaka, name="bolaka"),
    path('offers_page/', views.offers, name="offers_page"),
    path('bolakareview/', views.bolakareview, name="bolakareview"),
    path('ticket/', views.ticket, name="ticket"),
    path('deletebalaka/<str:pk>/', views.deletebalaka, name="deletebalaka"),
    path('ticket_page/', views.ticket_page, name="ticket_page"),


    # Air
    path('Air_Biman_Bangladesh/', views.Air_Biman_Bangladesh, name="Air_Biman_Bangladesh"),
    path('Air_Novoair/', views.Air_Novoair, name="Air_Novoair"),
    path('Air_US_Bangla/', views.Air_US_Bangla, name="Air_US_Bangla"),

    # Bus
    path('Bus_Akash/', views.Bus_Akash, name="Bus_Akash"),
    path('Bus_Alif/', views.Bus_Alif, name="Bus_Alif"),
    path('Bus_Anabil/', views.Bus_Anabil, name="Bus_Anabil"),
    path('Bus_BRTC/', views.Bus_BRTC, name="Bus_BRTC"),
    path('Bus_Green_Dhaka/', views.Bus_Green_Dhaka, name="Bus_Green_Dhaka"),
    path('Bus_Raida/', views.Bus_Raida, name="Bus_Raida"),
    path('Bus_Skyline/', views.Bus_Skyline, name="Bus_Skyline"),
    path('Bus_Supravat/', views.Bus_Supravat, name="Bus_Supravat"),
    path('Bus_VIP/', views.Bus_VIP, name="Bus_VIP"),

    # Train
    path('Train_Chitra_Express/', views.Train_Chitra_Express, name="Train_Chitra_Express"),
    path('Train_Ekota_Express/', views.Train_Ekota_Express, name="Train_Ekota_Express"),
    path('Train_Mahanagar_Godhuli/', views.Train_Mahanagar_Godhuli, name="Train_Mahanagar_Godhuli"),
    path('Train_Suborno_Express/', views.Train_Suborno_Express, name="Train_Suborno_Express"),
    path('Train_Tista_Express/', views.Train_Tista_Express, name="Train_Tista_Express"),

    path('(?P<slug>[\w-]+)/', views.homepage, name="list"),
]

ots/ots/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('', views.homepage),

]

urlpatterns += staticfiles_urlpatterns()

ots/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/ticket.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}
.txt-white{
    color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropdown {
  position: sticky;
  display: inline-block;
}
.dropdown-- {
  position: sticky;
  display: inline-block;
  float: right;
  height: 0px;
  width: 5%;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown---content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown---content a:hover {background-color: #f1f1f1}

.dropdown--:hover .dropdown-content {
  display: block;
}

.dropdown--:hover .dropbtn {
  background-color: #3e8e41;
}
.left-padding{
padding-right: 50px;
}

.roundbutton1{
border-radius: 50%;
}
</style>
</head>
<body>
<div class="topnav">
        <a class="active" href="/main">Home</a>

        <a href="{% url 'articles:about' %}">About</a>
        <a href="{% url 'articles:contact' %}">Contact Us</a>
        <a href="{% url 'articles:ticket_page' %}">Ticket Page</a>
        <a href="{% url 'articles:offers_page' %}">Your Offers</a>


    </div>
<div class="dropdown-- " >
  <button class="dropbtn roundbutton1" >{{ user.username }}</button>
  <div class="dropdown-content">
  <a><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
      <button type="submit" class="dropbtn ">Logout</button>
  </form></a>
  </div>
</div>

    <div class="Wrapper">

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>