ots/main/urls.py
#from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.homepage, name="list"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('bolaka/', views.bolaka, name="bolaka"),
    path('offers_page/', views.offers, name="offers_page"),
    path('bolakareview/', views.bolakareview, name="bolakareview"),
    path('ticket/', views.ticket, name="ticket"),
    path('deletebalaka/<str:pk>/', views.deletebalaka, name="deletebalaka"),
    path('ticket_page/', views.ticket_page, name="ticket_page"),


    # Air
    path('Air_Biman_Bangladesh/', views.Air_Biman_Bangladesh, name="Air_Biman_Bangladesh"),
    path('Air_Novoair/', views.Air_Novoair, name="Air_Novoair"),
    path('Air_US_Bangla/', views.Air_US_Bangla, name="Air_US_Bangla"),

    # Bus
    path('Bus_Akash/', views.Bus_Akash, name="Bus_Akash"),
    path('Bus_Alif/', views.Bus_Alif, name="Bus_Alif"),
    path('Bus_Anabil/', views.Bus_Anabil, name="Bus_Anabil"),
    path('Bus_BRTC/', views.Bus_BRTC, name="Bus_BRTC"),
    path('Bus_Green_Dhaka/', views.Bus_Green_Dhaka, name="Bus_Green_Dhaka"),
    path('Bus_Raida/', views.Bus_Raida, name="Bus_Raida"),
    path('Bus_Skyline/', views.Bus_Skyline, name="Bus_Skyline"),
    path('Bus_Supravat/', views.Bus_Supravat, name="Bus_Supravat"),
    path('Bus_VIP/', views.Bus_VIP, name="Bus_VIP"),

    # Train
    path('Train_Chitra_Express/', views.Train_Chitra_Express, name="Train_Chitra_Express"),
    path('Train_Ekota_Express/', views.Train_Ekota_Express, name="Train_Ekota_Express"),
    path('Train_Mahanagar_Godhuli/', views.Train_Mahanagar_Godhuli, name="Train_Mahanagar_Godhuli"),
    path('Train_Suborno_Express/', views.Train_Suborno_Express, name="Train_Suborno_Express"),
    path('Train_Tista_Express/', views.Train_Tista_Express, name="Train_Tista_Express"),

    path('(?P<slug>[\w-]+)/', views.homepage, name="list"),
]

ots/ots/urls.py
#from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('', views.homepage),

]

urlpatterns += staticfiles_urlpatterns()

ots/main/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)
    # add in thumbnail later
    # add in author later

    def __str__(self):
        return self.title


RATE_CHOICES=[
    (1, '1 - Trash'),
    (2, '2- Horrible'),
    (3, '3- Terrible'),
    (4, '4- Bad'),
    (5, '5- OK'),
    (6, '6- Rideable'),
    (7, '7- Good'),
    (8, '8- Very good'),
    (9, '9- Perfect'),
    (10, '10- Best'),

]

BUS_CHOICES=[
    ('Balaka', 'Balaka'),
    ('Akash', 'Akash'),
    ('Alif', 'Alif'),
    ('Raida', 'Raida'),
    ('VIP', 'VIP'),
    ('BRTC', 'BRTC')
]


class balaka(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=3000, blank=True)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)
    busname = models.CharField(choices=BUS_CHOICES,max_length=20, default= None, null=True)
    user = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

ots/main/forms.py
from django import forms
from . import models
from .models import balaka, RATE_CHOICES


class balakareview(forms.ModelForm):
    class Meta:
        model = models.balaka
        fields = ['name', 'text', 'rate', 'busname']

ots/main/views.py
from django.forms.widgets import Input
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template import loader

from .models import Article
from django.contrib.auth.decorators import login_required

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from django.core.mail import send_mail

from .models import balaka

from . import forms


# Create your views here.
@login_required(login_url="/accounts/login/")
def homepage(request):
    return render(request, 'main/homepage.html')


@login_required(login_url="/accounts/login/")
def bus_details(request, slug):
    # return HttpResponse(slug)
    return render(request, 'main/bus_details.html')


@login_required(login_url="/accounts/login/")
def about(request):
    # return HttpResponse("About")
    return render(request, 'main/about.html')


@login_required(login_url="/account/login/")
def contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message_phone = request.POST['message-phone']
        message = request.POST['message-message']

        #send email
        send_mail(
            'Mail Sent By '+message_name , # subject
            '\n'+'Senders Phone: '+message_phone + '\nSenders Email: '+message_email+ ' \nMessage: ' + message, #message
            message_email, #from mail
            ['2018-3-60-088@std.ewubd.edu'], #tomail
        )
        return render(request, 'main/contact.html', {'message_name': message_name})
    else:
        return render(request, 'main/contact.html')


@login_required(login_url="/account/login/")
def ticket_page(request):
    return render(request, 'main/ticket_page.html')


@login_required(login_url="/account/login/")
def ticket_page(request):
    ticket_page.message_name = request.POST.get('message-name')
    ticket_page.message_email = request.POST.get('message-email')
    ticket_page.message_phone = request.POST.get('message-phone')
    ticket_page.message_start = request.POST.get('message-start')
    ticket_page.message_end = request.POST.get('message-end')
    ticket_page.message_date = request.POST.get('message-date')
    ticket_page.message_bus = request.POST.get('message-bus')
    ticket_page.text = request.POST.get('message-text')

    return render(request, 'main/ticket_page.html', {'message_name': ticket_page.message_name})


@login_required(login_url="/account/login/")
def ticket(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 14)
    name = ticket_page.message_name
    mail = ticket_page.message_email
    phone = ticket_page.message_phone
    start = ticket_page.message_start
    end = ticket_page.message_end
    date = ticket_page.message_date
    bus = ticket_page.message_bus
    text = ticket_page.text
    # print(text)

    lines = [
        "Welcome to optimal transportation system",
        " ",
        "Your ticket is below",
        " ",
        "Full name: " + name,
        " ",
        "Email: " + mail,
        " ",
        "Phone: "+phone,
        " ",
        "Pickup place: "+start,
        " ",
        "Destination: "+end,
        " ",
        "Journey Date: "+date,
        " ",
        "Bus: "+bus,
        " ",
        ""+text,
        "",
        "All right reserved by optimal transportation system",

    ]

    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename="ticket.pdf")


# Air
@login_required(login_url="/account/login/")
def Air_Biman_Bangladesh(request):
    return render(request, 'main/Air_Biman_Bangladesh.html')


@login_required(login_url="/account/login/")
def Air_Novoair(request):
    return render(request, 'main/Air_Novoair.html')


@login_required(login_url="/account/login/")
def Air_US_Bangla(request):
    return render(request, 'main/Air_US_Bangla.html')


# Bus
@login_required(login_url="/account/login/")
def bolaka(request):

    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/bolaka.html', {'Balaka': Balaka})


@login_required(login_url="/account/login/")
def bolakareview(request):
    form = forms.balakareview()
    if request.method == 'POST':
        form = forms.balakareview(request.POST)
        if form.is_valid():
            # save to db
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # instance = balaka.objects.get(id=id)
            # instance.delete()
            next = request.POST.get('next', '/')
            return HttpResponseRedirect(next)
    else:
        form = forms.balakareview()
    return render(request, 'main/balakareview.html', {'form': form})


def deletebalaka(request, pk):
    instance = balaka.objects.get(id=pk)
    instance.delete()
    return redirect('articles:bolaka')


@login_required(login_url="/account/login/")
def Bus_Akash(request):
    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/Bus_Akash.html', {'Balaka': Balaka})


@login_required(login_url="/account/login/")
def Bus_Alif(request):
    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/Bus_Alif.html', {'Balaka': Balaka})


@login_required(login_url="/account/login/")
def Bus_Anabil(request):
    return render(request, 'main/Bus_Anabil.html')


@login_required(login_url="/account/login/")
def Bus_BRTC(request):
    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/Bus_BRTC.html', {'Balaka': Balaka})


@login_required(login_url="/account/login/")
def Bus_Green_Dhaka(request):
    return render(request, 'main/Bus_Green_Dhaka.html')


@login_required(login_url="/account/login/")
def Bus_Raida(request):
    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/Bus_Raida.html', {'Balaka': Balaka})



@login_required(login_url="/account/login/")
def Bus_Skyline(request):
    return render(request, 'main/Bus_Skyline.html')


@login_required(login_url="/account/login/")
def Bus_Supravat(request):
    return render(request, 'main/Bus_Supravat.html')


@login_required(login_url="/account/login/")
def Bus_VIP(request):
    Balaka = balaka.objects.all().order_by('date')
    return render(request, 'main/Bus_VIP.html', {'Balaka': Balaka})



# Train
@login_required(login_url="/account/login/")
def Train_Chitra_Express(request):
    return render(request, 'main/Train_Chitra_Express.html')


@login_required(login_url="/account/login/")
def Train_Ekota_Express(request):
    return render(request, 'main/Train_Ekota_Express.html')


@login_required(login_url="/account/login/")
def Train_Mahanagar_Godhuli(request):
    return render(request, 'main/Train_Mahanagar_Godhuli.html')


@login_required(login_url="/account/login/")
def Train_Suborno_Express(request):
    return render(request, 'main/Train_Suborno_Express.html')


@login_required(login_url="/account/login/")
def Train_Tista_Express(request):
    return render(request, 'main/Train_Tista_Express.html')


@login_required(login_url="/account/login/")
def offers(request):
    articles = Article.objects.all()
    return render(request, 'main/offers.html', {'articles': articles})

ots/main/templates/main/Air_US_Bangla.html
{% extends 'base_layout.html' %}
{% block content %}
    
	<section class="tm-section tm-section-1">
                <div class="tm-textbox tm-textbox-2 tm-bg-dark">
                  <h2 class="tm-text-blue mb-4" align="center">US-Bangla Airlines</h2>
				  <h2 class="tm-text-blue mb-4">Route Number</h2>
                  <p class="mb-4">
                    A-192
                  </p>
				  <h2 class="tm-text-blue mb-4">Route Distribution</h2>
                  <p class="mb-4">
                    DHAKA - COX'S BAZAR - DHAKA, DHAKA - BARISHAL - DHAKA, DHAKA - RAJSHAHI - DHAKA, DHAKA - JASHORE - DHAKA, DHAKA - SYLHET - DHAKA, DHAKA - SAIDPUR - DHAKA, DHAKA - CHATTOGRAM - DHAKA</p>
				  <h2 class="tm-text-blue mb-4">Details</h2>
                  <p class="mb-4">
                    Residents of Dhaka have to take a bus to get from one place to another in Dhaka for work or livelihood. The bus services operating in Dhaka are known as city buses. Numerous city buses ply on multiple routes in Dhaka. There are three types of bus services in Dhaka according to the quality of passenger service. These are seating service, counter service and local bus service.
                  </p>
                    <h2 class="tm-text-blue mb-4">US-Bangla Airlines</h2>
				  <img src="/static/us bangla airlines.jpg">
                    <br>
				  <div class="topnav">
                      <div class="centerb">
                            <button type="submit"><a href="{% url 'articles:ticket_page' %}">Buy Ticket</a></button>
                        </div>

                  </div>

                </div>
              </section>

{% endblock %}

ots/main/templates/main/Bus_Akash.html
{% extends 'base_layout.html' %}
{% block content %}

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- site metas -->
  <title>shree</title>
  <!-- bootstrap css -->
  <link rel="stylesheet" href="/static/bus-bootstrap.min.css">
  <!-- style css -->
  <link rel="stylesheet" href="/static/style-bus.css">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- about  -->
<div id="about" class="about">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="about-box">
          <h2>Akash</h2>
		  <p></p>
				<h2>Route Number</h2>
				  <p class="mb-4">
                    A-198
                  </p>
				  <h2>Route Distribution</h2>
                  <p>
                    Kadamtali - Keraniganj - Babubazar - Naya Bazar - Golap Shah Mazar - GPO - Paltan - Kakrail - Shantinagar - Malibagh Moor - Mouchak - Malibagh Railgate - Hazipara - Rampura Bazar - Rampura Bridge - Merul - Badda - Shahjadpur - Bashtola - Notun Bazar - Nadda - Bashundhara - Jamuna Future Park - Kuril Bishwa Road - Khilkhet - Airport - Jashimuddin (Uttara) - Rajlakshmi - Azampur - House Building - Abdullahpur - Tongi</p>
				  <h2>Details</h2>
                  <p>
                    Residents of Dhaka have to take a bus to get from one place to another in Dhaka for work or livelihood. The bus services operating in Dhaka are known as city buses. Numerous city buses ply on multiple routes in Dhaka. There are three types of bus services in Dhaka according to the quality of passenger service. These are seating service, counter service and local bus service.
                  </p>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 padding_rl">
        <div class="about-box_img">
          <figure><img src="/static/akash.png"></figure>

        </div>
      </div>
    </div>
	<div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
	  <div class="about-box">
	  <div style="background-color:white;">
                         <h1>Reviews: </h1>
                        {% for Balaka in Balaka %}
                        {% ifequal Balaka.busname 'Akash' %}
                            <div>
                                <h3>{{ Balaka.name }}
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                {% ifequal user Balaka.user %}
                                <a href="{% url 'articles:deletebalaka' Balaka.id %}"><div class="icon-trash" style="float: right">
    <div class="trash-lid" style="background-color: #02A7D7"></div>
    <div class="trash-container" style="background-color: #02A7D7"></div></a>
                                {% endifequal %}</h3>
                                <h4>{{ Balaka.text }}</h4>
                                <h4>Rating: {{Balaka.rate }}</h4>
                                <h4>{{ Balaka.date }}</h4>


                                <br>
                            </div>
                        {% endifequal %}
                        {% endfor %}

                    </div>
		<button class="button-ticket button2-ticket" type="submit"><a href="{% url 'articles:bolakareview' %}">Write a review</a></button>
		<button class="button-ticket button2-ticket" type="submit"><a href="{% url 'articles:ticket_page' %}">Buy Ticket</a></button>
		</div>
	  </div>
	  </div>
  </div>
</div>
    <style>
    .icon-trash {
  width: 48px;
  height: 48px;
  position: relative;
  overflow: hidden;
  margin-left: 25px;
  margin-bottom: 25px;
}

.icon-trash .trash-lid {
  width: 62%;
  height: 10%;
  position: absolute;
  left: 50%;
  margin-left: -31%;
  top: 10.5%;
  background-color: #000;
  border-top-left-radius: 80%;
  border-top-right-radius: 80%;
  -webkit-transform: rotate(-5deg);
  -moz-transform: rotate(-5deg);
  -ms-transform: rotate(-5deg);
  transform: rotate(-5deg);
}

.icon-trash .trash-lid:after {
  content: "";
  width: 26%;
  height: 100%;
  position: absolute;
  left: 50%;
  margin-left: -13%;
  margin-top: -10%;
  background-color: inherit;
  border-top-left-radius: 30%;
  border-top-right-radius: 30%;
  -webkit-transform: rotate(-1deg);
  -moz-transform: rotate(-1deg);
  -ms-transform: rotate(-1deg);
  transform: rotate(-1deg);
}

.icon-trash .trash-container {
  width: 56%;
  height: 65%;
  position: absolute;
  left: 50%;
  margin-left: -28%;
  bottom: 10%;
  background-color: #000;
  border-bottom-left-radius: 15%;
  border-bottom-right-radius: 15%;
}

.icon-trash .trash-container:after {
  content: "";
  width: 110%;
  height: 12%;
  position: absolute;
  left: 50%;
  margin-left: -55%;
  top: 0;
  background-color: inherit;
  border-bottom-left-radius: 45%;
  border-bottom-right-radius: 45%;
}

.icon-trash .trash-line-1 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 38%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.icon-trash .trash-line-2 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 50%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.icon-trash .trash-line-3 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 62%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.button-ticket {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s;
  transition-duration: 0.4s;
}

.button2-ticket:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

    </style>


{% endblock %}

ots/main/templates/main/Bus_Anabil.html
{% extends 'base_layout.html' %}
{% block content %}
    
	<section class="tm-section tm-section-1">
                <div class="tm-textbox tm-textbox-2 tm-bg-dark">
                  <h2 class="tm-text-blue mb-4" align="center">Anabil</h2>
				  <h2 class="tm-text-blue mb-4">Route Number</h2>
                  <p class="mb-4">
                    A-256
                  </p>
				  <h2 class="tm-text-blue mb-4">Route Distribution</h2>
                  <p class="mb-4">
                    Sign Board - Shonir Akhra - Jatrabari - Sayedabad - Mugdapara - Bashabo - Khilgaon - Malibagh Railgate - Hazipara - Rampura Bazar - Rampura Bridge - Merul - Badda - Uttar Badda - Shahjadpur - Bashtola - Notun Bazar - Nadda - Bashundhara - Jamuna Future Park - Kuril Bishwa Road - Khilkhet - Airport - Jashimuddin (Uttara) - Rajlakshmi - Azampur - House Building - Abdullahpur - Tongi - station Road - Mill Gate - Board Bazar - Gazipur Bypass - Gazipur Chourasta</p>
				  <h2 class="tm-text-blue mb-4">Details</h2>
                  <p class="mb-4">
                    Residents of Dhaka have to take a bus to get from one place to another in Dhaka for work or livelihood. The bus services operating in Dhaka are known as city buses. Numerous city buses ply on multiple routes in Dhaka. There are three types of bus services in Dhaka according to the quality of passenger service. These are seating service, counter service and local bus service.
                  </p>
                    <h2 class="tm-text-blue mb-4">Anabil</h2>
				  <img src="/static/anabil.jpg">
                    <br>
				  <div class="topnav">
                      <div class="centerb">
                            <button type="submit"><a href="{% url 'articles:ticket_page' %}">Buy Ticket</a></button>
                        </div>

                  </div>

                </div>
              </section>

{% endblock %}

ots/main/templates/main/Bus_BRTC.html
{% extends 'base_layout.html' %}
{% block content %}

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- site metas -->
  <title>shree</title>
  <!-- bootstrap css -->
  <link rel="stylesheet" href="/static/bus-bootstrap.min.css">
  <!-- style css -->
  <link rel="stylesheet" href="/static/style-bus.css">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- about  -->
<div id="about" class="about">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="about-box">
          <h2>BRTC</h2>
		  <p></p>
				<h2>Route Number</h2>
				  <p class="mb-4">
                    A-257
                  </p>
				  <h2>Route Distribution</h2>
                  <p>
                   Mohammadpur - Asad Gate - Khamar Bari - Farmgate - Jahangir Gate - Mohakhali - Wireless - Gulshan 1 - Badda Link Road - Uttar Badda - Shahjadpur - Bashtola - Notun Bazar - Nadda - Bashundhara - Jamuna Future Park - Kuril Bishwa Road</p>
				  <h2>Details</h2>
                  <p>
                    Residents of Dhaka have to take a bus to get from one place to another in Dhaka for work or livelihood. The bus services operating in Dhaka are known as city buses. Numerous city buses ply on multiple routes in Dhaka. There are three types of bus services in Dhaka according to the quality of passenger service. These are seating service, counter service and local bus service.
                  </p>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 padding_rl">
        <div class="about-box_img">
          <figure><img src="/static/brtc.jpg"></figure>

        </div>
      </div>
    </div>
	<div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
	  <div class="about-box">
	  <div style="background-color:white;">
                         <h1>Reviews: </h1>
                        {% for Balaka in Balaka %}
                        {% ifequal Balaka.busname 'BRTC' %}
                            <div>
                                <h3>{{ Balaka.name }}
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                {% ifequal user Balaka.user %}
                                <a href="{% url 'articles:deletebalaka' Balaka.id %}"><div class="icon-trash" style="float: right">
    <div class="trash-lid" style="background-color: #02A7D7"></div>
    <div class="trash-container" style="background-color: #02A7D7"></div> </a>
                                {% endifequal %}</h3>
                                <h4>{{ Balaka.text }}</h4>
                                <h4>Rating: {{Balaka.rate }}</h4>
                                <h4>{{ Balaka.date }}</h4>


                                <br>
                            </div>
                        {% endifequal %}
                        {% endfor %}

                    </div>
		<button class="button-ticket button2-ticket" type="submit"><a href="{% url 'articles:bolakareview' %}">Write a review</a></button>
		<button class="button-ticket button2-ticket" type="submit"><a href="{% url 'articles:ticket_page' %}">Buy Ticket</a></button>
		</div>
	  </div>
	  </div>
  </div>
</div>
    <style>
    .icon-trash {
  width: 48px;
  height: 48px;
  position: relative;
  overflow: hidden;
  margin-left: 25px;
  margin-bottom: 25px;
}

.icon-trash .trash-lid {
  width: 62%;
  height: 10%;
  position: absolute;
  left: 50%;
  margin-left: -31%;
  top: 10.5%;
  background-color: #000;
  border-top-left-radius: 80%;
  border-top-right-radius: 80%;
  -webkit-transform: rotate(-5deg);
  -moz-transform: rotate(-5deg);
  -ms-transform: rotate(-5deg);
  transform: rotate(-5deg);
}

.icon-trash .trash-lid:after {
  content: "";
  width: 26%;
  height: 100%;
  position: absolute;
  left: 50%;
  margin-left: -13%;
  margin-top: -10%;
  background-color: inherit;
  border-top-left-radius: 30%;
  border-top-right-radius: 30%;
  -webkit-transform: rotate(-1deg);
  -moz-transform: rotate(-1deg);
  -ms-transform: rotate(-1deg);
  transform: rotate(-1deg);
}

.icon-trash .trash-container {
  width: 56%;
  height: 65%;
  position: absolute;
  left: 50%;
  margin-left: -28%;
  bottom: 10%;
  background-color: #000;
  border-bottom-left-radius: 15%;
  border-bottom-right-radius: 15%;
}

.icon-trash .trash-container:after {
  content: "";
  width: 110%;
  height: 12%;
  position: absolute;
  left: 50%;
  margin-left: -55%;
  top: 0;
  background-color: inherit;
  border-bottom-left-radius: 45%;
  border-bottom-right-radius: 45%;
}

.icon-trash .trash-line-1 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 38%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.icon-trash .trash-line-2 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 50%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.icon-trash .trash-line-3 {
  width: 4%;
  height: 50%;
  position: absolute;
  left: 62%;
  margin-left: -2%;
  bottom: 17%;
  background-color: #252527;
}

.button-ticket {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s;
  transition-duration: 0.4s;
}

.button2-ticket:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}

    </style>


{% endblock %}

ots/main/templates/main/bus_details.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="bus-detail">
    <div class="bus">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
    </div>
    </div>


{% endblock %}